# Generated by Django 5.2.1 on 2025-06-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_customuser_combinedfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='usertype',
            field=models.CharField(default='', max_length=50),
        ),
    ]
