# Generated by Django 5.2.1 on 2025-07-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_lineupform_port_berth_form_saileddata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port_berth_form',
            name='Berth_Type',
        ),
    ]
