# Generated by Django 5.2.1 on 2025-07-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_port_berth_form_berth_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='port_berth_form',
            name='BerthRemarks',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='port_berth_form',
            name='LOBerth',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='port_berth_form',
            name='PermissibleDraft',
            field=models.CharField(default='', max_length=20),
        ),
    ]
